query Test {
	test
}

mutation MutationTest($text: String) {
	_test(text: $text)
}

query ServerVersion {
	serverInfo {
		version
	}
}

query ServerInstance {
	serverInfo {
		instance
	}
}

query ServerTime {
	serverInfo {
		dateTime
	}
}

query ServerLocales {
	serverInfo {
		locales
	}
}

query ServerInfo {
	serverInfo {
		Name: name
		Version: version
		Description: description
		ServerTime: dateTime
		ServerTimeZone: timeZone
		sslValidFrom
		sslValidTo
		apiEndPoint
		apiEndPointEncrypted
		subscriptionsEndPoint
		subscriptionsEndPointEncrypted
	}
}

mutation StopServer {
	_stopServer
}

mutation RestartServer {
	_restartServer
}
