query Test {
	test
}

mutation MutationTest($text: String) {
	_test(text: $text)
}

query ServerVersion {
	serverInfo {
		version
		instance
	}
}

query ServerTime {
	serverInfo {
		dateTime
	}
}

query ServerLocales {
	serverInfo {
		locales
	}
}

query ServerInfo {
	serverInfo {
		name
		version
		description
		url
		hostname
		port
		dateTime
		timeZone
		sslValidFrom
		sslValidTo
		apiEndPoint
		apiEndPointEncrypted
		subscriptionsEndPoint
		subscriptionsEndPointEncrypted
		dataBase
	}
}

mutation StopServer {
	_stopServer
}

mutation RestartServer {
	_restartServer
}
