query ErrorsLog($input: GetServerLog) {
	serverLog(type: "errors", input: $input)
}

query QueriesLog($input: GetServerLog) {
	serverLog(type: "queries", input: $input)
}

query ViewLogRow($type: String = "errors", $date: String) {
	serverLog(type: $type, input: { date: [$date] })
}

mutation ClearErrorsLog {
	_clearServerLog(type: "errors")
}

mutation ClearQueriesLog {
	_clearServerLog(type: "queries")
}
