query ErrorsLog($input: GetServerLog) {
	serverLog(type: "errors", input: $input)
}

query QueriesLog($input: GetServerLog) {
	serverLog(type: "queries", input: $input)
}

query ViewLogRow($type: String = "errors", $date: String) {
	serverLog(type: $type, input: { date: [$date] })
}

query LogInfo {
	errors: serverLog(
		type: "errors"
		input: {
			params: { limit: 1, offset: 0, order: { column: "date", sort: "DESC" } }
		}
	)
	queries: serverLog(
		type: "queries"
		input: {
			params: { limit: 1, offset: 0, order: { column: "date", sort: "DESC" } }
		}
	)
}

mutation ClearLog($type: String = "errors") {
	_clearServerLog(type: $type)
}
