query ErrorsLog($input: GetServerLog) {
	serverLog(type: "errors", input: $input)
}

query QueriesLog($input: GetServerLog) {
	serverLog(type: "queries", input: $input)
}

query ViewLogRow($type: String = "errors", $date: String) {
	serverLog(type: $type, input: { date: [$date] })
}

query LogConfig {
	config: serverInfo {
		apiLoger
	}
}

query LatestLogs($type: String = "errors") {
	logs: serverLog(
		type: $type
		input: {
			params: { limit: 1, offset: 0, order: { column: "date", sort: "DESC" } }
		}
	)
}

mutation ClearLog($type: String = "errors") {
	_clearServerLog(type: $type)
}
