fragment PushTemplateI18n on PushTemplate_i18n {
	id
	title {
		lang
		value
	}
	body {
		lang
		value
	}
	event
	app
	platform
	active
	createdAt: info {
		date: createdAt
	}
	updatedAt: info {
		date: updatedAt
	}
}

fragment PushSubscriberFragment on PushSubscriber {
	id
	token
	event
	user
	app
	platform
	lang
	active
	createdAt: info {
		date: createdAt
	}
	updatedAt: info {
		date: updatedAt
	}
}

query PushData {
	pushTemplateData
}

query PushTemplates($input: GetPushTemplateInput) {
	templates: pushTemplates_i18n(input: $input) {
		count
		rows {
			...PushTemplateI18n
		}
	}
}

query PushTemplatesCount($input: GetPushTemplateInput) {
	templates: pushTemplates(input: $input) {
		count
	}
}

query PushTemplate($input: GetPushTemplateInput) {
	template: pushTemplate_i18n(input: $input) {
		...PushTemplateI18n
	}
}

query PushTemplatesByEventExist(
	$events: [String]
	$apps: [String]
	$platforms: [String]
) {
	templates: pushTemplates(
		input: { event: $events, app: $apps, platform: $platforms, active: true }
	) {
		count
		rows {
			id
			event
			app
			platform
		}
	}
}

mutation AddPushTemplate($input: PushTemplateInput) {
	_addPushTemplate(input: $input)
}

mutation EditPushTemplate($id: ID!, $input: PushTemplateInput) {
	_editPushTemplate(id: $id, input: $input)
}

mutation RemovePushTemplateByID($id: [ID]!) {
	_removePushTemplate(id: $id)
}

query PushSubscribers($input: GetSubscribePushInput) {
	subscribers: pushSubscribers(input: $input) {
		count
		rows {
			...PushSubscriberFragment
		}
	}
}

query PushSubscribersCount($input: GetSubscribePushInput) {
	subscribers: pushSubscribers(input: $input) {
		count
		rows {
			user
		}
	}
}

query PushSubscriber($id: ID) {
	subscriber: pushSubscriber(input: { id: [$id] }) {
		...PushSubscriberFragment
	}
}

query PushSubscriberUsers($id: [ID]) {
	users(input: { id: $id }) {
		rows {
			id
			fullName
		}
	}
}

query Send($event: String, $users: [ID], $vars: JSON, $data: JSON) {
	sent: pushTest(event: $event, users: $users, vars: $vars, data: $data)
}

mutation Subscribe($input: SubscribePushInput) {
	_subscribePush(input: $input)
}

mutation RemoveSubscribersByID($id: [ID]) {
	_removeSubscribePush(input: { id: $id })
}
