fragment user on User {
	id
	role
	fullName
	role
	permission {
		rules
	}
}

query CurrentUser {
	user {
      ...user
    }
}

mutation Logout {
	_logout
}

query PingToken {
	ping
}

query AuthTokenInfo($token: String) {
	tokenInfo(token: $token)
}

query AuthUser($input: GetUser) {
	user(input: $input) {
		id
		mail
		loginAt
		firstName
		lastName
		fullName
		role
		registerWith
		active
	}
}

query AuthInfo {
	serverInfo {
		JWT
	}
}

mutation Login($mail: String!, $pass: String!) {
	_login(mail: $mail, pass: $pass) {
		user {
			...user
		}
		tokens {
			accessToken
			refreshToken
		}
	}
}

mutation RefreshToken($token: String!) {
	_refreshToken(refreshToken: $token) {
		accessToken
		refreshToken
	}
}